name: unittests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ gha_update2 ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11', '3.10', '3.9']
    steps:
    -
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    -
      uses: actions/checkout@v3
    -
      name: Install and test
      run: |
        python setup.py install
        python -m unittest
